### ISSUE TITLE
Node 16 required?

### ISSUE THREAD

**Issue by B4nan** [reside-eng/jest-runtime#14]
Any particular reason for requiring node 16? The package seems to be working just fine on node 14 too ([a CI run as a proof](https://github.com/mikro-orm/mikro-orm/runs/6827188253?check_suite_focus=true)), and I dont see anything that would require higher version.

**Comment by a88zach** [comment]
The issue this custom runtime solves was introduced in node 16.10.0.  If you are on node 14, this custom runtime should not be needed.  Are you seeing a reduced heap size when using this runtime with node v14?

**Comment by a88zach** [comment]
I see the issue.  You are trying to test your code on node 14, 16, and 18.  

https://github.com/reside-eng/jest-runtime/pull/16

**Comment by prescottprue** [comment]
https://github.com/reside-eng/jest-runtime/releases/tag/v1.0.1

**Comment by B4nan** [comment]
Thank you!
